esphome:
  name: eh_laundry
  comment: ESPHome Laundry
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret access_password

ota:
  password: !secret access_password

sensor:
  - platform: wifi_signal
    name: "Laundry WiFi Signal"
    update_interval: 10s
  - platform: dht
    model: DHT22_TYPE2
    pin: D7
    temperature:
      name: "Laundry Temperature"
    humidity:
      name: "Laundry Humidity"
    update_interval: 10s
  - platform: adc
    pin: A0
    name: "Laundry Brightness"
    unit_of_measurement: lux
    filters:
      - multiply: 5.0
      - lambda: "return (2500.0/x-500.0)/10.0;"
    update_interval: 10s

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Laundry Motion"
    device_class: motion

output:
  - platform: esp8266_pwm
    pin: D1
    id: redgpio
  - platform: esp8266_pwm
    pin: D2
    id: greengpio
  - platform: esp8266_pwm
    pin: D3
    id: bluegpio

light:
  - platform: rgb
    name: "Laundry Indicator Light"
    red: redgpio
    green: greengpio
    blue: bluegpio
